"""add soft delete flag in WorkingHoursModel

Revision ID: 17a2bfcdaf68
Revises: dc74fb824b89
Create Date: 2024-11-01 18:42:31.484888

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17a2bfcdaf68'
down_revision = 'dc74fb824b89'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('working_hours', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                'is_active',
                sa.Boolean(),
                nullable=False,
                server_default=sa.sql.expression.true()
            )
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('working_hours', schema=None) as batch_op:
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###
