"""add role field to user model

Revision ID: 32bdbaee62b5
Revises: ad548d8111dd
Create Date: 2024-10-15 14:18:39.992951

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '32bdbaee62b5'
down_revision = 'ad548d8111dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    roletype = postgresql.ENUM('ADMIN', 'APPROVER', 'CLIENT', 'OWNER', 'STAFF', name='roletype')
    roletype.create(op.get_bind())

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                'role',
                sa.Enum(
                'ADMIN', 'APPROVER', 'CLIENT', 'OWNER', 'STAFF', name='roletype'
                ),
                server_default='CLIENT',
                nullable=False
            )
        )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('role')

    # ### end Alembic commands ###
