"""add TimestampMixin in AppointmentModel

Revision ID: 66726e480e7f
Revises: e19381369f33
Create Date: 2024-11-02 13:50:21.701543

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66726e480e7f'
down_revision = 'e19381369f33'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_on', sa.DateTime(), server_default=sa.text("timezone('UTC', now())"), nullable=False))
        batch_op.add_column(sa.Column('updated_on', sa.DateTime(), server_default=sa.text("timezone('UTC', now())"), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.drop_column('updated_on')
        batch_op.drop_column('created_on')

    # ### end Alembic commands ###
