"""UserModel Soft delete flag

Revision ID: a36fbe6efa88
Revises: 7e0895dc7668
Create Date: 2024-10-17 18:16:23.727604

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "a36fbe6efa88"
down_revision = "7e0895dc7668"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("service_providers", schema=None) as batch_op:
        batch_op.alter_column(
            "floor",
            existing_type=sa.VARCHAR(length=10),
            type_=sa.String(length=255),
            existing_nullable=True,
        )

    with op.batch_alter_table("users", schema=None) as batch_op:
        # Add the 'is_active' column with a default value of True for existing records
        batch_op.add_column(
            sa.Column(
                "is_active", sa.Boolean(), nullable=False, server_default=sa.true()
            )
        )

        # Once all records are updated, remove the server default to avoid future inserts setting it automatically
        batch_op.alter_column("is_active", server_default=None)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_column("is_active")

    with op.batch_alter_table("service_providers", schema=None) as batch_op:
        batch_op.alter_column(
            "floor",
            existing_type=sa.String(length=255),
            type_=sa.VARCHAR(length=10),
            existing_nullable=True,
        )

    # ### end Alembic commands ###
