"""Add timestamp fields to models: Service, ServiceCategory, ServiceSubCategory

Revision ID: b51a575c3e51
Revises: 5b7a9b25c496
Create Date: 2024-10-29 11:07:48.501549

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "b51a575c3e51"
down_revision = "5b7a9b25c496"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("categories", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "created_on",
                sa.DateTime(),
                server_default=sa.text("timezone('UTC', now())"),
                nullable=False,
            )
        )
        batch_op.add_column(
            sa.Column(
                "updated_on",
                sa.DateTime(),
                server_default=sa.text("timezone('UTC', now())"),
                nullable=False,
            )
        )

    with op.batch_alter_table("services", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "created_on",
                sa.DateTime(),
                server_default=sa.text("timezone('UTC', now())"),
                nullable=False,
            )
        )
        batch_op.add_column(
            sa.Column(
                "updated_on",
                sa.DateTime(),
                server_default=sa.text("timezone('UTC', now())"),
                nullable=False,
            )
        )

    with op.batch_alter_table("subcategories", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "created_on",
                sa.DateTime(),
                server_default=sa.text("timezone('UTC', now())"),
                nullable=False,
            )
        )
        batch_op.add_column(
            sa.Column(
                "updated_on",
                sa.DateTime(),
                server_default=sa.text("timezone('UTC', now())"),
                nullable=False,
            )
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("subcategories", schema=None) as batch_op:
        batch_op.drop_column("updated_on")
        batch_op.drop_column("created_on")

    with op.batch_alter_table("services", schema=None) as batch_op:
        batch_op.drop_column("updated_on")
        batch_op.drop_column("created_on")

    with op.batch_alter_table("categories", schema=None) as batch_op:
        batch_op.drop_column("updated_on")
        batch_op.drop_column("created_on")

    # ### end Alembic commands ###
