"""add soft delete flag in ServiceSubCategoryModel

Revision ID: be88106db52d
Revises: db5ebb5c0b86
Create Date: 2024-10-30 18:02:31.427388

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be88106db52d'
down_revision = 'db5ebb5c0b86'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subcategories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subcategories', schema=None) as batch_op:
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###
