"""add soft delete flag in ServiceProviderModel

Revision ID: d700a95315e6
Revises: 24660f95e2e4
Create Date: 2024-10-29 23:02:40.838186

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "d700a95315e6"
down_revision = "24660f95e2e4"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("service_providers", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "is_active",
                sa.Boolean(),
                nullable=False,
                server_default=sa.sql.expression.true(),
            )
        )

    with op.batch_alter_table("service_providers", schema=None) as batch_op:
        batch_op.alter_column("is_active", server_default=None)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("service_providers", schema=None) as batch_op:
        batch_op.drop_column("is_active")

    # ### end Alembic commands ###
