"""Add unique constraint to inquiry_id in ServiceProviderModel to ensure each inquiry can be associated with only one service provider.

Revision ID: d865ea189579
Revises: d700a95315e6
Create Date: 2024-10-30 14:28:38.361859

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd865ea189579'
down_revision = 'd700a95315e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_providers', schema=None) as batch_op:
        batch_op.alter_column('inquiry_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.create_unique_constraint(None, ['inquiry_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_providers', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('inquiry_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
