"""Set provider_id and employee_id to non-nullable in WorkingHoursModel

Revision ID: dc74fb824b89
Revises: d59c26d68f4a
Create Date: 2024-11-01 17:06:08.238665

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc74fb824b89'
down_revision = 'd59c26d68f4a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('working_hours', schema=None) as batch_op:
        batch_op.alter_column('provider_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('employee_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('working_hours', schema=None) as batch_op:
        batch_op.alter_column('employee_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('provider_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
